### ISSUE TITLE
Not working on Android, need libvoice.so file for different architecture

### ISSUE THREAD

**Issue by raviverma89** [jefflinwood/cordova-plugin-twiliovoicesdk#55]
on android it is not working, shows below error :
halted due to an error
    com.getkeepsafe.relinker.MissingLibraryException: lib/armeabi/libvoice.so
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:85)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at com.twilio.voice.UserAgent.loadLibrary(UserAgent.java:261)
        at com.twilio.voice.UserAgent.<init>(UserAgent.java:57)
        at com.twilio.voice.UserAgent.get(UserAgent.java:107)
        at com.twilio.voice.CallCommandHandlerImpl.run(CallCommandHandlerImpl.java:50)

can you please provide libvoice.so for below architectures
├── arm64-v8a
│ └── libvoice.so
├── armeabi-v7a
│ └── libvoice.so
├── armeabi
│ └── libvoice.so
├── x86
│ └── libvoice.so
└── x86_64
└── libvoice.so

**Comment by raviverma89** [comment]
it worked when i changed armeabi to armeabi-v7a in build.gradle

ndk {
abiFilters "armeabi-v7a", "x86"
}
