### ISSUE TITLE
How to Setup?

### ISSUE THREAD

**Issue by MoneyWasted** [jefflinwood/cordova-plugin-twiliovoicesdk#92]
Hello, I'm trying to implement this into my company's app and I'm not seeing any installation instructions for this plugin. When I try to do `cordova plugin add cordova-plugin-twiliovoicesdk` I get an error like this 

```
Failed to install 'cordova-plugin-twiliovoicesdk': Error: pod: Command failed with exit code 1 Error output:
Ignoring ffi-1.14.2 because its extensions are not built. Try: gem pristine ffi --version 1.14.2
    at ChildProcess.whenDone (/Users/hvcs/Documents/GitHub/Apps/iOS/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
pod: Command failed with exit code 1 Error output:
Ignoring ffi-1.14.2 because its extensions are not built. Try: gem pristine ffi --version 1.14.2
```

Any ideas on why I might be getting this error?

**Comment by MoneyWasted** [comment]
PS. when I try to use `gem pristine ffi --version 1.14.2` I get this...
```
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["ffi"] = 1.14.2
```

**Comment by jefflinwood** [comment]
Hi! That's actually a problem with Ruby, Cocoapods, and M1 Macs (the new ones).

Here's a workaround to use the Intel architecture for Cocoapods, for the time being:

https://medium.com/p-society/cocoapods-on-apple-silicon-m1-computers-86e05aa10d3e

You may need something similar when you run cordova.

**Comment by MoneyWasted** [comment]
Thanks for the reply! I figured out the issue. I had an outdated version of something don't remember what it was but I updated and now it works.
